PROJECT = rest_api
PROJECT_DESCRIPTION = Marcestats REST API
PROJECT_VERSION = 0.1.0

# Whitespace to be used when creating files from templates.
SP = 4

DEPS = cowboy
dep_cowboy_commit = 2.6.1

DEP_PLUGINS = cowboy

include erlang.mk
