# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-06 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgplays', '0009_auto_20160625_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[(b'B', b'Board game'), (b'R', b'Role-playing game')], default=b'B', max_length=1),
        ),
    ]
