# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgplays', '0011_play_virtual'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bgg_id',
            field=models.IntegerField(null=True),
        ),
    ]
