# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgplays', '0012_game_bgg_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='bgg_id',
            new_name='geek_id',
        ),
    ]
